version: '3'

services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - DATABASE_URL=postgres://my_user:my_password@postgres:5432/my_database
    networks:
      - my_network
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "GamaBackend.wsgi:application"]  # Reemplaza 'your_project_name' por el nombre de tu proyecto Django

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - my_network

  gama:
    image: gamaplatform/gama:1.9.3
    container_name: gama_headless
    restart: unless-stopped
    volumes:
      - ./gama:/working_dir
    ports:
      - "6868:6868"
    command: ["-socket", "6868"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
