version: '3'

services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=gama_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
      - DATABASE_URL=postgres://admin:12345678@postgres_db:5432/gama_database
    volumes:
      - ./backend/media:/app/media  # Volumen para persistir archivos subidos
      - ./backend/static:/app/static  # Volumen para archivos estáticos
    networks:
      - my_network
    command: >
      sh -c ". /app/venv/bin/activate &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 GamaBackend.wsgi:application"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gama_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  nginx:
    build: ./nginx
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - my_network

  gama:
    build: ./gama
    container_name: gama_headless
    restart: unless-stopped
    volumes:
      - ./gama:/working_dir
    ports:
      - "6868:6868"
    command: ["-socket", "6868"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge