version: '3'

services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://admin:12345678@postgres_db:5432/gama_database
      - DJANGO_SETTINGS_MODULE=GamaBackend.settings
    volumes:
      - ./backend/media:/app/media  # Volumen para persistir archivos subidos
      - ./backend/static:/app/static  # Volumen para archivos estáticos
      - ./backend/simulation_results:/app/simulation_results  # Volumen para persistir resultados de simulación
      - ./gama:/working_dir  # Volumen compartido para el script gama-headless.sh
    networks:
      - my_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gama_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - my_network

  nginx:
    build: ./nginx
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge