# Generated by Django 5.1.3 on 2024-11-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0002_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='Red', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='Car', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.TextField(default='Car', max_length=250),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1800),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('author', models.TextField(max_length=200)),
                ('publication_date', models.DateField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamaApp.publisher')),
            ],
        ),
    ]
