# Generated by Django 5.1.3 on 2024-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0003_publisher_alter_car_color_alter_car_is_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
