# Generated by Django 5.1.3 on 2024-12-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='users_with_access',
            field=models.ManyToManyField(related_name='allowed_simulations', to='GamaApp.customuser'),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='GamaApp.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='roles', to='GamaApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='RoleParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_control', models.BooleanField(default=False)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_parameters', to='GamaApp.parameter')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_parameters', to='GamaApp.role')),
            ],
        ),
    ]
