# Generated by Django 5.1.3 on 2024-12-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0007_alter_simulation_users_with_access_parameter_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='file',
            field=models.FileField(upload_to='Projects/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='Projects/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='GamaApp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='GamaApp.project'),
        ),
    ]
