# Generated by Django 5.1.3 on 2024-12-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0010_remove_book_publisher_delete_car_delete_dog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='description',
        ),
        migrations.AddField(
            model_name='parameter',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='data_type',
            field=models.CharField(default='int', max_length=50),
        ),
        migrations.AddField(
            model_name='parameter',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='variable_name',
            field=models.CharField(default='variable', max_length=100),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='Parametros', max_length=100),
        ),
    ]
