# Generated by Django 5.1.3 on 2024-12-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0011_remove_parameter_description_parameter_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_change_parameters',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='GamaApp.customuser'),
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change_parameters', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamaApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamaApp.customuser')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(related_name='assigned_users', through='GamaApp.UserProject', to='GamaApp.project'),
        ),
    ]
