# Generated by Django 5.1.3 on 2024-12-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0012_customuser_can_change_parameters_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
