# Generated by Django 5.1.3 on 2024-12-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamaApp', '0013_parameter_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_simulation', to='GamaApp.simulation')),
            ],
        ),
    ]
